"""add to_win_override

Revision ID: 33ffa62aed8f
Revises: 8e8cce422646
Create Date: 2026-09-09 16:49:32.933679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ffa62aed8f'
down_revision = '8e8cce422646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_win_override', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.drop_column('to_win_override')

    # ### end Alembic commands ###
